#!/usr/bin/env python3
"""Regenerate the acceptance-criteria index from the per-sprint breakdown files.

The index (acceptance-criteria.md) is a pure aggregation of the per-sprint
files under acceptance-criteria-breakdown/. Keeping it in sync by hand is
error-prone, so this regenerates it losslessly: it preserves each US and AC
heading verbatim, counts ACs, pulls the sprint focus titles from
sprint-breakdown.md, and auto-detects numbering gaps to emit `> Note:` lines.

Usage:
  python build_ac_index.py [--business-dir docs/business] [--write]

Without --write it prints the regenerated index to stdout for inspection.
"""
import argparse
import glob
import os
import re
import sys

SPRINT_FILE_RE = re.compile(r"acceptance-criteria-sprint-(\d+)\.md$")
US_HEAD_RE = re.compile(r"^##\s+(US-\d+)\b(.*)$")
AC_HEAD_RE = re.compile(r"^###\s+(AC-(\d+)\.(\d+))\b(.*)$")
BREAKDOWN_HEAD_RE = re.compile(r"^##\s+Sprint\s+(\d+)\s*[-—]\s*(.+?)\s*$")


def load_focus_titles(business_dir):
    """Map sprint number -> focus title from sprint-breakdown.md, if present."""
    path = os.path.join(business_dir, "sprint-breakdown.md")
    titles = {}
    if not os.path.exists(path):
        return titles
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = BREAKDOWN_HEAD_RE.match(line)
            if m:
                titles[int(m.group(1))] = m.group(2).strip()
    return titles


def parse_sprint_file(path):
    """Return (us_order, us_text, ac_by_us) for one sprint breakdown file."""
    us_order = []          # [us_id] in document order
    us_text = {}           # us_id -> full heading remainder (title + persona)
    ac_by_us = {}          # us_id -> [(ac_id, seq_int, ac_remainder)]
    current_us = None
    with open(path, encoding="utf-8") as f:
        for line in f:
            mu = US_HEAD_RE.match(line)
            if mu:
                current_us = mu.group(1)
                if current_us not in us_text:
                    us_order.append(current_us)
                    us_text[current_us] = mu.group(2).strip()
                    ac_by_us[current_us] = []
                continue
            ma = AC_HEAD_RE.match(line)
            if ma and current_us:
                ac_by_us[current_us].append(
                    (ma.group(1), int(ma.group(3)), ma.group(4).strip())
                )
    return us_order, us_text, ac_by_us


def gap_notes(us_id, acs):
    """Emit a note for every missing sequence number inside a US."""
    seqs = sorted(s for _, s, _ in acs)
    notes = []
    for prev, cur in zip(seqs, seqs[1:]):
        for missing in range(prev + 1, cur):
            num = us_id.split("-")[1]
            notes.append(
                f"> Note: AC-{num}.{missing:02d} is not present in the source; "
                f"numbering skips from .{prev:02d} to .{cur:02d}."
            )
    return notes


def build(business_dir):
    breakdown_dir = os.path.join(business_dir, "acceptance-criteria-breakdown")
    files = []
    for p in glob.glob(os.path.join(breakdown_dir, "acceptance-criteria-sprint-*.md")):
        m = SPRINT_FILE_RE.search(p)
        if m:
            files.append((int(m.group(1)), p))
    files.sort()
    if not files:
        sys.exit(f"No sprint files found under {breakdown_dir}")

    focus = load_focus_titles(business_dir)
    out = []
    out.append("# Acceptance Criteria — Index")
    out.append("")
    out.append(
        "This file is an index. The full Given/When/Then bodies live in the "
        "per-sprint files under "
        "[`acceptance-criteria-breakdown/`](acceptance-criteria-breakdown/). "
        "Each entry lists `AC-ID — Scenario`; click through for the full scenario."
    )
    out.append("")
    out.append("> Generated by build_ac_index.py. Edit the per-sprint files, not this index.")
    out.append("")

    # Sprints at a Glance
    glance = []
    sections = []
    for sprint, path in files:
        us_order, us_text, ac_by_us = parse_sprint_file(path)
        ac_count = sum(len(v) for v in ac_by_us.values())
        us_list = ", ".join(us_order)
        rel = os.path.relpath(path, business_dir)
        title = focus.get(sprint, "")
        glance.append((sprint, title, us_list, ac_count, os.path.basename(path), rel))

        sec = []
        heading = f"## Sprint {sprint}" + (f" — {title}" if title else "")
        sec.append(heading)
        sec.append("")
        sec.append(f"[Full bodies →]({rel})")
        sec.append("")
        for us in us_order:
            sec.append(f"### {us} {us_text[us]}".rstrip())
            sec.append("")
            for ac_id, _, remainder in ac_by_us[us]:
                sec.append(f"- {ac_id} {remainder}".rstrip())
            notes = gap_notes(us, ac_by_us[us])
            if notes:
                sec.append("")
                sec.extend(notes)
            sec.append("")
        sections.append("\n".join(sec).rstrip())

    out.append("## Sprints at a Glance")
    out.append("")
    out.append("| Sprint | Focus | User Stories | AC Count | File |")
    out.append("| ------ | ----- | ------------ | -------- | ---- |")
    for sprint, title, us_list, ac_count, base, rel in glance:
        out.append(f"| {sprint} | {title} | {us_list} | {ac_count} | [{base}]({rel}) |")
    out.append("")
    out.append("---")
    out.append("")
    out.append("\n\n".join(sections))
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--business-dir", default="docs/business")
    ap.add_argument("--write", action="store_true",
                    help="write acceptance-criteria.md in place instead of printing")
    args = ap.parse_args()

    text = build(args.business_dir)
    if args.write:
        target = os.path.join(args.business_dir, "acceptance-criteria.md")
        with open(target, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"Wrote {target}")
    else:
        print(text)


if __name__ == "__main__":
    main()
